version: '3'
services:

  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "~/Desktop/inception/website:/var/www/html"
    depends_on:
      - wordpress
    networks:
      - InceptionNet
    restart: always
  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    ports:
      - "9000:9000"
    volumes:
      - ~/Desktop/INcep001/website:/var/www/html/wordpress/
    depends_on:
      - mariadb
    networks:
      - InceptionNet
    restart: always
    env_file:
      - .en
      
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - "~/Desktop/inception/mariadb:/var/lib/mysql"
    networks:
      - backend
    restart: always
    env_file:
      - .env
    networks:
      - InceptionNet
  wordpress:
    build: 
      context:  ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    env_file:
      - .env
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    volumes:
      - ~/Desktop/INcep001/website:/var/www/html/wordpress/
networks:
  InceptionNet:
