version: '3'

services:
  mariadb: # ! mariaDB
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    ports:
      - 3306:3306
    networks:
      - INceptionNet
    env_file:
      - .env
    volumes:
      - INception_db:/var/lib/mysql
    restart: always

  nginx: # ! Nginx
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/sites-available/default
      - INception_wp:/var/www/html/wordpress
    networks:
      - INceptionNet
    restart: always
  wordpress: # ! Wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    env_file:
      - .env
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    volumes:
      - INception_wp:/var/www/html/wordpress
    networks:
      - INceptionNet
    restart: always
  adminer: # ! Adminer
    build: ./requirements/bonus/adminer
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080
    networks:
      - INceptionNet
    restart: always
  staticweb: # ! Static Site
    build: ./requirements/bonus/staticsite
    container_name: staticweb
    image: staticweb
    ports:
      - 8000:8000
    volumes:
      - INception_static:/var/www/html
    networks:
      - INceptionNet
    restart: always
  portainer:  # ! Portainer 
    build: ./requirements/bonus/portainer
    container_name: portainer
    image: portainer
    ports:
      - "4242:9443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - INception_portainer:/data
    networks:
      - INceptionNet
    restart: always
  redis: # ! redis
    build: ./requirements/bonus/redis
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - INception_redis:/etc/redis
    networks:
      - INceptionNet
    restart: always
# ! networks :
networks:
  INceptionNet:
    driver: bridge
# ! volumes :
volumes:
  INception_wp: 
    driver_opts:
      type: 'none'
      o: bind
      device:  /Users/mmasstou/Desktop/inception/volumes/wp
  INception_static:
    driver_opts:
      type: 'none'
      o: bind
      device:  /Users/mmasstou/Desktop/inception/volumes/static
  INception_portainer:
    driver_opts:
      type: 'none'
      o: bind
      device:  /Users/mmasstou/Desktop/inception/volumes/portainer
  INception_db:
    driver_opts:
      type: 'none'
      o: bind
      device:  /Users/mmasstou/Desktop/inception/volumes/db
  INception_redis:
    driver_opts:
      type: 'none'
      o: bind
      device:  /Users/mmasstou/Desktop/inception/volumes/redis