version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: NGINX_container
    ports:
      - "443:443"
    volumes:
      - ~/Desktop/INcep001/website:/var/www/html/wordpress/
    networks:
      - InceptionNet
    depends_on:
      - wordpress
  mariadb:
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: DB_container
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - InceptionNet
  wordpress:
    build: 
      context:  ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    env_file:
      - .env
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    volumes:
      - ~/Desktop/INcep001/website:/var/www/html/wordpress/
networks:
  InceptionNet:

