FROM debian:buster

RUN apt-get update
RUN apt-get install -y mariadb-server

EXPOSE 3306

COPY ./tools/create-db.sql /tmp


RUN service mysql start && mysql < /tmp/create-db.sql && rm -f /tmp/create-db.sql;

COPY ./tools/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

CMD ["mysqld"]