
CREATE DATABASE IF NOT EXISTS wpDB;
CREATE USER IF NOT EXISTS 'mmasstou'@'localhost' IDENTIFIED BY 'mmasstou0123';
GRANT ALL PRIVILEGES ON wpDB.* TO 'mmasstou'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root0123';
